# 1 相关分析——Spearman、Pearson系数

In [1]:
try:
    import pandas as pd
    import numpy as np
except:
    !pip3 install pandas numpy matplotlib

In [2]:
Data = {
    '平均气温x': [3.80, 4.00, 5.80, 8.00, 11.30, 14.40, 16.50, 16.20, 13.80, 10.80, 6.70, 4.70],
    '降雨量y': [77.70, 51.20, 60.10, 54.10, 55.40, 56.80, 45.00, 55.30, 67.50, 73.30, 76.60, 79.60]
}
data = pd.DataFrame(Data)
data

    平均气温x  降雨量y
0     3.8  77.7
1     4.0  51.2
2     5.8  60.1
3     8.0  54.1
4    11.3  55.4
5    14.4  56.8
6    16.5  45.0
7    16.2  55.3
8    13.8  67.5
9    10.8  73.3
10    6.7  76.6
11    4.7  79.6

In [3]:
# Pearson相关系数
data.corr('pearson')

          平均气温x      降雨量y
平均气温x  1.000000 -0.489495
降雨量y  -0.489495  1.000000

__Spearman相关系数看下面 2 pandas--read_excel最后。__  
前面的部分是Python打开Excel常用的操作

# 2 pandas——read_excel

```Python3
pandas.read_excel(io, sheet_name=0, header=0, names=None, index_col=None, usecols=None, squeeze=False, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skiprows=None, nrows=None, na_values=None, keep_default_na=True, verbose=False, parse_dates=False, date_parser=None, thousands=None, comment=None, skipfooter=0, convert_float=True, mangle_dupe_cols=True, **kwds)
```  
用途：Read an Excel file into a pandas DataFrame  
支持格式：xls、xlsx、xlsm、xlsb和odf，可以是来自本地，也可以来自网络UR。
支持读入单个或多个工作表。  

## 2.1 数据准备  
    定位到工作表

__内容：__  
1. 路径io：接受任何的字符串路径，不论是本地的file还是其他的ftp、http、s3等等。
2. 工作表sheet_name：接受 str、int、list，or None, defult 0
    1. 字符串对应工作表名称；
    2. 整型对应工作表索引；
    3. 包含字符串或者整型的列表对应多个工作表；
    4. None 表示解析所有工作表；
 
    
 注：如果使用解析多个工作表，将以字典的形式输出

In [4]:
# sheet_name表明需要解析那张表格，默认为0（第一张）
data1 = pd.read_excel('W:/home/Ubuntu/Documents/test.xlsx', sheet_name=2)
data1

FileNotFoundError: [Errno 2] No such file or directory: '/home/Ubuntu/Documents/test.xlsx'

__内容：__ 
   3. 列标签header: 默认defult 0，可以接受一个整数或者一个整数列表，整数所在的行作为列标签，整数列表则是表示多重标签。如果不需要列名，使用None。
   4. 自定义列名names: 
      1. 基于header的基础上，接收列表，定义列名；
      2. 不能与header=None同时使用；
      3. names的长度必须和Excel列长度一致。
   5. 行标签index_col: 与header类似。
   6. 强制规定列数据类型converters，传入字典{列：类型}，dtype类似。

In [ ]:
# 列标签header
data2 = pd.read_excel('W:/home/Ubuntu/Documents/test.xlsx', 2, header=None)
data2

In [ ]:
# 自定义列名names
data3 = pd.read_excel('W:/home/Ubuntu/Documents/test.xlsx', 2, names=[1,2,3,4,5,6,7,8,9,10,11,12,13])
data3

## 2.2 数据筛选  
    定位到某一区域
### 2.2.1 解析特定列usecols

可传入 str、list

其中，
1. 如果是str，表示Excel列字母和列范围的列表（如："A:E" 或 "A,C,E:F")；
2. 列表可以是字符串或整型，字符串表示列名称，整型表示列索引。


注：解析特定行用nrows参数。

In [ ]:
data4 = pd.read_excel('W:/home/Ubuntu/Documents/test.xlsx', sheet_name=2, usecols=['GDP(x)(亿元)', '总人口(Y)(万人)'])
data4

### 2.2.2 跳过开头结尾的的行
  以哪行开始、以哪行结束  

skiprows：list-like  
  + Rows to skip at the beginning (0-indexed).  
      
skipfooterint, default 0  
  + Rows at the end to skip (0-indexed).

In [ ]:
data5 = pd.read_excel('W:/home/Ubuntu/Documents/test.xlsx', sheet_name=2, usecols=['GDP(x)(亿元)', '总人口(Y)(万人)'], skipfooter=1)
data5

In [ ]:
# 计算 spearman 相关系数
data5.corr('spearman')

# 3 回归分析   
## 3.1 一元线性回归

In [ ]:
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# 完整sheet在pandas中查看
data6 = pd.read_excel('W:/home/Ubuntu/Documents/test.xlsx', sheet_name=1)
data6

In [ ]:
# 数据筛选
data7 = pd.read_excel('W:/home/Ubuntu/Documents/test.xlsx', sheet_name=1, usecols=['纬度y/度', '年降水量p/mm'], skipfooter=9)
data7

In [ ]:
# 散点图观察趋势
plt.scatter(
    data7['纬度y/度'],
    data7['年降水量p/mm'],
)
plt.xlabel('latitud')
plt.ylabel('amount of precipitation')

In [ ]:
# 计算参数
x = data7['纬度y/度'].values
y = data7['年降水量p/mm'].values

#############参数说明#############
# slope：斜率                    #
# intercept：截距                #
# r_value：相关系数              #
# p_value：假设检验P值           #
# sts_err：标准误差              #
##################################

slope, intercept, r_value, p_value, std_err = stats.linregress(x,y)

In [ ]:
# 输入R

In [ ]:
# 曲线拟合
plt.scatter(
    data7['纬度y/度'],
    data7['年降水量p/mm'],
)

predictions = slope*data7['纬度y/度'] + intercept
plt.plot(
    data7['纬度y/度'],
    predictions,
    c='black',
    linewidth=2
)
plt.xlabel('纬度y/度')
plt.ylabel('年降水量p/mm')

In [ ]:
# 回归模型 和 R²
print("The linear model is: y = {:.5}x + {:.5}".format(slope, intercept))
print("r-squared:", r_value**2)

__补充：__  
Python实现一元线性回归的8种方法：
  1. Simple matrix inverse;
  2. Stats.linregress;
  3. Numpy.linalg.lstsq;
  4. Moore-Penrose inverse;
  5. sklearn.linear_model;
  6. Polyfit;
  7. Statsmodels.OLS;
  8. Optimize.curve_fit。

排名按速度快慢的顺序，其中Statsmodels.OLS()结果像R或Julia等统计语言一样丰富。所以你也可以搭配使用，你可以用sklearn。linalg_model来进行训练预测，用statsmodel.OLS来进行模型评估的。

参考文章：
https://blog.csdn.net/tMb8Z9Vdm66wH68VX1/article/details/79102425   
原文地址：  
https://medium.freecodecamp.org/data-science-with-python-8-ways-to-do-linear-regression-and-measure-their-speed-b5577d75f8b

## 3.2 多元线性分析  
__Tip：__ 进行多元线性回归分析时就不能再用Stats.linregress了，它只能进行一元线性回归分析。进行多元线性回归以及非线性关系的线性化都可以用sklearn.linear_modle

In [5]:
# 数据清洗
data8 = pd.read_excel('W:/home/Ubuntu/Documents/test.xlsx', sheet_name=1, usecols=['纬度y/度', '海拔a/m', '年降水量p/mm'], skipfooter=9)
data8

    纬度y/度   海拔a/m  年降水量p/mm
0   40.50  1170.8     48.25
1   36.60  1707.2    193.72
2   35.53  1908.8    413.94
3   37.48  2072.4    358.60
4   35.43  2136.4    615.04
5   33.82   930.8    752.42
6   35.63  2025.1    435.43
7   36.57  1397.8    238.55
8   39.77  1477.2     87.85
9   36.05  1517.2    316.00
10  34.20  1410.0    503.73
11  35.38  1886.6    554.04
12  35.62  1917.0    502.07
13  34.00  3471.4    611.78
14  34.38  2314.6    603.66
15  34.73  1250.0    501.67
16  34.58  1131.7    540.16
17  37.20  2726.7    264.15
18  35.12  1765.0    427.11
19  35.42  2450.0    513.09
20  34.73  1495.0    478.21
21  35.85  1873.7    395.25
22  33.75   970.0    650.14
23  33.40  1079.0    480.24
24  41.80  1770.0     85.79
25  41.58  2159.0    144.38
26  40.15  1138.7     39.17
27  40.26  1526.0     65.32
28  40.72  1591.0     71.88
29  40.00  1270.2     58.57
30  40.30  1177.4     54.33
31  39.37  1332.2    106.33
32  38.83  2311.8    257.21
33  39.15  1453.7    114.53
34  38.93  1482.7    127.49
35  38.78  1764.6    194.90
36  38.45  2271.0    331.09
37  38.63  1367.0    110.57
38  38.23  1976.1    194.42
39  37.92  1530.8    163.89
40  37.20  3045.1    389.90
41  36.58  1255.6    541.50
42  35.73  1421.9    573.03
43  35.73  1346.6    521.31
44  35.15  1360.0    645.21
45  35.52  1650.0    466.28
46  32.95  1014.3    558.83
47  34.03  1753.2    621.02
48  34.70  2810.2    515.02
49  35.00  2915.7    545.72
50  34.21  3362.7    786.75
51  35.43  1221.2    584.89
52  36.14  1111.7    574.00

因为变量较多，为了简化代码我们用更高级的绘图库seaborn.pairplot, 这里散点图我们用seaborn中的pairplot, [方法文档](https://www.cntofu.com/book/172/docs/23.md)

In [ ]:
# !pip3 install seaborn

__注意：__ matplotlib中文乱码，可以修改全局文件也可直接设置参数，
设置参数的前提是系统里面有所选参数文件，我这里是wsl，直接修改的matplotlib.

In [ ]:
# 散点图观察趋势
import seaborn as sns

## 解决matplotlib中文乱码
sns.set_style("darkgrid",{"font.sans-serif":'simhei'})

## 散点图
sns.pairplot(data8, x_vars=['纬度y/度', '海拔a/m'], y_vars='年降水量p/mm', kind='scatter')